default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %> 
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'bookstore_development' %>

test:
  <<: *default
  database: bookstore_test

staging:
  <<: *default

production:
  <<: *default
